# 应用服务 WEB 访问端口
server:
  port: 8080
  #配置这个路径的话，直接访问public、static等路径下的资源时要在前面加上这个路径
  #如果未配置就直接localhost:8888/index.html访问即可
#  servlet:
#    context-path: /dormitory


mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #指定Mybatis的实体目录,这样在resultType或者resultMap的type中直接写实体类名称，
  #例如User即可，前面不用再加包名
  type-aliases-package: com.lanliushu.entity

spring:
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    #name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/dor?useUnicode=true&characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    # 数据库用户名&密码：
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    #初始化时建立物理连接的个数。
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，
    #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    #有两个含义： 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于
    #minEvictableIdleTimeMillis则关闭物理连接 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    #连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。
    #如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: SELECT 1 FROM DUAL
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
    #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #配置这个可以对网页提交的put或delete等请求生效
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#     这个是自己指定静态资源目录位置
#    static-path-pattern: /public/**

#  redis:
#    # Redis默认情况下有16个分片，这里配置具体使用的分片。默认是索引为0的分片
#    database: 1
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: lanliushu
#    # 连接超时时间（毫秒）
#    timeout: 2000s
#
#    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
#    lettuce:
#      pool:
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: 60s
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 10
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 10
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-activ: 8
